Feature/udp support
logzio/logzio-nodejs pull request #18
Opened 2016-09-22 20:47 UTC by gillyb

This took a long time, but I finally got to doing it. :)
Testing it on a production account I created for this, and all messages were received.

2016-09-25 05:13 UTC, asafm commented on lib/logzio-nodejs.js
> +                throw new Error('Failed to send udp log message. err = ' + err);
Throwing an exception might the application which uses you. Let's use the same methodology below and call the callback with the error message and exception

2016-09-25 05:16 UTC, asafm commented on lib/logzio-nodejs.js
> +    }
Maybe add debug - "Sent x messages via UDP" ?

2016-09-25 05:18 UTC, asafm commented on lib/logzio-nodejs.js
> +    this.port = this.protocol === 'udp' ? 5050 : (this.protocol === 'http' ? 8070 : 8071);
I think it's nicer to have a map of protocols to ports. 
We can re-use this map to validate allowed protocols as well above

2016-09-25 05:51 UTC, asafm commented on README.md
> +* **protocol** - 'http', 'https' or 'udp'. Default: http
I think when we introduce udp, there are different sets of params. For example: bufferSize and numberOfRetries isn't not relevant. Maybe we should make it clear in the documentation which params are for http and which for UDP.

2016-09-25 05:51 UTC, asafm commented on lib/logzio-nodejs.js
> +    if (this.protocol === 'udp') {
Since UDP is not bulk, I would send the UDP message immediately as it logged.

2016-09-25 05:52 UTC, asafm commented on README.md
> +**0.3.11**
I think UDP calls for 0.4

2016-09-25 05:54 UTC, asafm requested changes
Looks good - left some comments.
The prominent thing missing here is testing. We can do the same we did for http and use a mock udp server

2016-09-26 19:54 UTC, gillyb commented on lib/logzio-nodejs.js
> +    if (this.protocol === 'udp') {
I thought about that, but then thought maybe some people will still want to send all the udp messages once every 60 seconds, so their network isn't always sending udp.
If they still want it to send each message they can use `bufferSize=1` - I will add this to the documentation.

2016-09-26 19:54 UTC, gillyb commented on README.md
> +**0.3.11**
👍

2016-09-26 20:52 UTC, gillyb commented
@asafm I went over the comments, and implemented them all. I also added two unit tests to test the new UDP functionality. In addition, I added some more info to the documentation regarding usage of udp, and bumped the version to 0.4.
You want to take a look, can I merge this ?

2016-10-04 20:11 UTC, merged

2016-10-09 05:35 UTC, asafm reviewed
Looks good.
Regarding the test it self - I prefer to avoid mocking since it exposes internal code. Maybe a simple udp server would do the trick - I saw npm has one for this very much like we use in the http testing.