add option to set/unset user-agent header
logzio/logzio-nodejs pull request #96
Opened 2022-06-08 10:40 UTC by resdenia

2022-06-08 12:16 UTC, yotamloe commented on lib/logzio-nodejs.js
> +		setUserAgent = true,
Please fix the indentation :)

2022-06-08 12:16 UTC, yotamloe commented on lib/logzio-nodejs.js
> +		this.setUserAgent = setUserAgent;
Please fix the indentation :)

2022-06-08 12:18 UTC, yotamloe requested changes
Overall looks good, Please add a description to this PR and a unit test for the new feature.

2022-06-08 12:48 UTC, yotamloe commented on test/logger.test.js
> +            assert.equal(logger._createBulk.getCall(0).args[0][0].message, logMsg);
This `assert` is validating the log message and not the `user-agent` header

2022-06-08 13:41 UTC, yotamloe approved these changes
LGTM

2022-06-12 19:11 UTC, Doron-Bargo requested changes
Please update readme

2022-06-12 19:11 UTC, Doron-Bargo commented on README.md
> +* **setUserAgent** - To sending logs we are providing for user to send logs with user-agent. To send logs without user-agent please change to `false`.  Default:`true`,
This is not clear

2022-06-13 09:22 UTC, AlonMiz commented on lib/logzio-nodejs.js
> +        } else {
Y else just add the user agent to the object?

2022-06-13 09:24 UTC, AlonMiz commented on lib/logzio-nodejs.js
>                  'content-type': 'text/plain',
Eg.
```suggestion
                'content-type': 'text/plain',
                ...(userAgent? {'user-agent': USER_AGENT} : {})
```

2022-06-13 13:19 UTC, resdenia commented on lib/logzio-nodejs.js
>                  'content-type': 'text/plain',
Yes!
Thank you @AlonMiz !

2022-06-16 08:33 UTC, Doron-Bargo approved these changes
lgtm

2022-06-16 12:32 UTC, Doron-Bargo approved these changes
lgtm

2022-06-23 08:32 UTC, Doron-Bargo approved these changes
lgtm

2022-06-26 06:24 UTC, merged